CREATE TABLE `t_user`
(
    `id` bigint generated by default as identity NOT NULL,
    `username` varchar(32)  NOT NULL,
    `password` varchar(255)  NOT NULL,
    `created_at` TIMESTAMP  NOT NULL,
    `updated_at` TIMESTAMP  NOT NULL,
    `email` varchar(255) DEFAULT NULL,
    `status` int NOT NULL
);
